### ISSUE TITLE
CME: java.util.ConcurrentModificationException (During Normal Play)

### ISSUE THREAD

**Issue by KaneHart** [EmosewaPixel/GregBlock#1]
I did nothing but put down half slab I thought was my pc stalling for a sec but then the game shutdown and it was a total crash. 

Honestly CME's are annoying as heck and unless you can find the source of it your screwed. Don't use it's BQ because it shows up that is just what was ticking in the background it could be anything at this point.

https://www.youtube.com/watch?v=Gy79WL94ZqM

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  RandomPatches (randompatches-1.12.2-1.5.0.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/23/18 6:06 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at betterquesting.questing.QuestInstance.isUnlocked(QuestInstance.java:736)
	at betterquesting.questing.QuestInstance.update(QuestInstance.java:216)
	at betterquesting.handlers.EventHandler.onLivingUpdate(EventHandler.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_337_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at betterquesting.questing.QuestInstance.isUnlocked(QuestInstance.java:736)
	at betterquesting.questing.QuestInstance.update(QuestInstance.java:216)
	at betterquesting.handlers.EventHandler.onLivingUpdate(EventHandler.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_337_EventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:567)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 379
	Entity Name: Kane_Hart
	Entity's Exact location: -995.46, 84.50, -998.24
	Entity's Block location: World: (-996,84,-999), Chunk: (at 12,5,9 in -63,-63; contains blocks -1008,0,-1008 to -993,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1ed48c45
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4722500344 bytes (4503 MB) / 6433669120 bytes (6135 MB) up to 8375238656 bytes (7987 MB)
	JVM Flags: 16 total; -XX:+AggressiveOpts -XX:ParallelGCThreads=3 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx8192m
	IntCache: cache: 13, tcache: 95, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2759 103 mods loaded, 103 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State          | ID                         | Version                  | Source                                            | Signature                                |
	|:-------------- |:-------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAA | minecraft                  | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAA | mcp                        | 9.42                     | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.4.2759-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | forge                      | 14.23.4.2759             | forge-1.12.2-14.23.4.2759-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | randompatches              | 1.12.2-1.5.0.4           | randompatches-1.12.2-1.5.0.4.jar                  | None                                     |
	| UCHIJAAAAAAAAA | elucore                    | 1.0                      | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAA | charset                    | 0.5.5.5                  | Charset-Lib-0.5.5.5.jar                           | None                                     |
	| UCHIJAAAAAAAAA | crafttweaker               | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAA | mtlib                      | 3.0.5                    | MTLib-3.0.5.jar                                   | None                                     |
	| UCHIJAAAAAAAAA | modtweaker                 | 4.0.13                   | modtweaker-4.0.14.jar                             | None                                     |
	| UCHIJAAAAAAAAA | jei                        | 4.12.0.216               | jei_1.12.2-4.12.0.216.jar                         | None                                     |
	| UCHIJAAAAAAAAA | appleskin                  | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCHIJAAAAAAAAA | appliedenergistics2        | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar             | None                                     |
	| UCHIJAAAAAAAAA | badwithernocookiereloaded  | 1.12.2-3.1.14            | badwithernocookiereloaded-1.12.2-3.1.14.jar       | None                                     |
	| UCHIJAAAAAAAAA | base                       | 3.10.0                   | base-1.12.2-3.10.0.jar                            | None                                     |
	| UCHIJAAAAAAAAA | bdlib                      | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| UCHIJAAAAAAAAA | betterbuilderswands        | 0.12.0                   | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar   | None                                     |
	| UCHIJAAAAAAAAA | betterquesting             | 3.5.263                  | BetterQuesting-3.5.263.jar                        | None                                     |
	| UCHIJAAAAAAAAA | forestry                   | 5.8.1.344                | forestry_1.12.2-5.8.1.344.jar                     | None                                     |
	| UCHIJAAAAAAAAA | binniecore                 | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | binniedesign               | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | genetics                   | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | botany                     | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | extrabees                  | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | extratrees                 | 2.5.0.168                | binnie-mods-1.12.2-2.5.0.168.jar                  | None                                     |
	| UCHIJAAAAAAAAA | blockcraftery              | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
	| UCHIJAAAAAAAAA | buildinggadgets            | 1.6.2                    | BuildingGadgets-1.6.2.jar                         | None                                     |
	| UCHIJAAAAAAAAA | carryon                    | 1.10                     | Carry On MC1.12.2 v1.10.jar                       | None                                     |
	| UCHIJAAAAAAAAA | ceramics                   | 1.12-1.3.4               | Ceramics-1.12-1.3.4.jar                           | None                                     |
	| UCHIJAAAAAAAAA | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHIJAAAAAAAAA | ctm                        | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
	| UCHIJAAAAAAAAA | chisel                     | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| UCHIJAAAAAAAAA | clumps                     | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
	| UCHIJAAAAAAAAA | codechickenlib             | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAA | redstoneflux               | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | cofhcore                   | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar            | None                                     |
	| UCHIJAAAAAAAAA | cofhworld                  | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | consolefilter              | 1.1.1                    | ConsoleFilter-1.12.2-1.1.1.jar                    | None                                     |
	| UCHIJAAAAAAAAA | containerfix               | 1.0                      | ContainerFix MC1.12.2 v1.0.jar                    | None                                     |
	| UCHIJAAAAAAAAA | contenttweaker             | 1.12.2-4.8.0             | ContentTweaker-1.12.2-4.8.0.jar                   | None                                     |
	| UCHIJAAAAAAAAA | controlling                | 3.0.6                    | Controlling-3.0.6.jar                             | None                                     |
	| UCHIJAAAAAAAAA | craftingtweaks             | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
	| UCHIJAAAAAAAAA | ctgui                      | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAA | crafttweakerjei            | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAA | custommainmenu             | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                 | None                                     |
	| UCHIJAAAAAAAAA | defaultoptions             | 9.2.7                    | DefaultOptions_1.12.2-9.2.7.jar                   | None                                     |
	| UCHIJAAAAAAAAA | defaultworldgenerator-port | 1.12-2.3                 | DefaultWorldGenerator-port-1.12-2.3.jar           | None                                     |
	| UCHIJAAAAAAAAA | forgelin                   | 1.7.4                    | Forgelin-1.7.4.jar                                | None                                     |
	| UCHIJAAAAAAAAA | exnihilocreatio            | 1.12-0.3.2               | exnihilocreatio-1.12-0.3.2.jar                    | None                                     |
	| UCHIJAAAAAAAAA | excompressum               | 3.0.24                   | ExCompressum_1.12.2-3.0.24.jar                    | None                                     |
	| UCHIJAAAAAAAAA | extracells                 | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                   | None                                     |
	| UCHIJAAAAAAAAA | fastfurnace                | 1.1.0                    | FastFurnace-1.12.2-1.1.0.jar                      | None                                     |
	| UCHIJAAAAAAAAA | fastleafdecay              | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| UCHIJAAAAAAAAA | fastbench                  | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                    | None                                     |
	| UCHIJAAAAAAAAA | forgivingvoid              | 1.0.18                   | ForgivingVoid_1.12.2-1.0.18.jar                   | None                                     |
	| UCHIJAAAAAAAAA | ftblib                     | 5.3.0.53                 | FTBLib-5.3.0.53.jar                               | None                                     |
	| UCHIJAAAAAAAAA | ftbutilities               | 5.3.0.51                 | FTBUtilities-5.3.0.51.jar                         | None                                     |
	| UCHIJAAAAAAAAA | trashcansreborn            | 1.1.0                    | garbagebins-1.1.0.jar                             | None                                     |
	| UCHIJAAAAAAAAA | gregtech                   | 0.5.9.88                 | gregtech-1.12.2-0.5.9.88.jar                      | None                                     |
	| UCHIJAAAAAAAAA | gtadditions                | 1.12.2-1.0.0             | GregicAdditions-1.12.2-1.0.0.jar                  | None                                     |
	| UCHIJAAAAAAAAA | gregblockutils             | 1.12.2-1.0.0             | GregBlockUtilities-1.12.2-1.0.0.jar               | None                                     |
	| UCHIJAAAAAAAAA | gtcebees                   | 1.12.2-1.0.0             | GTCEBees-1.12.2-1.0.0.jar                         | None                                     |
	| UCHIJAAAAAAAAA | harvest                    | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                         | None                                     |
	| UCHIJAAAAAAAAA | incontrol                  | 0.1.0                    | incontrol-1.12-3.8.1.jar                          | None                                     |
	| UCHIJAAAAAAAAA | teslacorelib               | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAA | industrialforegoing        | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.11.2-212.jar         | None                                     |
	| UCHIJAAAAAAAAA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAAAAAAA | itlt                       | 1.0.0                    | itlt-1.12-1.0.0.jar                               | None                                     |
	| UCHIJAAAAAAAAA | jeibees                    | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| UCHIJAAAAAAAAA | kleeslabs                  | 5.4.11                   | KleeSlabs_1.12.2-5.4.11.jar                       | None                                     |
	| UCHIJAAAAAAAAA | mcjtylib_ng                | 3.0.5                    | mcjtylib-1.12-3.0.5.jar                           | None                                     |
	| UCHIJAAAAAAAAA | moreoverlays               | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
	| UCHIJAAAAAAAAA | morpheus                   | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UCHIJAAAAAAAAA | mousetweaks                | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
	| UCHIJAAAAAAAAA | nmsot                      | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
	| UCHIJAAAAAAAAA | nuclearcraft               | 2.11g                    | NuclearCraft-2.11g--1.12.2.jar                    | None                                     |
	| UCHIJAAAAAAAAA | oreexcavation              | 1.4.129                  | OreExcavation-1.4.129.jar                         | None                                     |
	| UCHIJAAAAAAAAA | p455w0rdslib               | 2.0.35                   | p455w0rdslib-1.12-2.0.35.jar                      | None                                     |
	| UCHIJAAAAAAAAA | packmode                   | 1.2.0                    | packmode-1.12.2-1.2.0.jar                         | None                                     |
	| UCHIJAAAAAAAAA | placebo                    | 1.4.1                    | Placebo-1.12.2-1.4.1.jar                          | None                                     |
	| UCHIJAAAAAAAAA | pneumaticcraft             | 1.12.2-0.8.0-267         | pneumaticcraft-repressurized-1.12.2-0.8.0-267.jar | None                                     |
	| UCHIJAAAAAAAAA | questbook                  | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                          | None                                     |
	| UCHIJAAAAAAAAA | questutils                 | 0.2.0                    | questutils-0.2.0.jar                              | None                                     |
	| UCHIJAAAAAAAAA | randomtweaks               | 1.12.2-2.1.5.0           | randomtweaks-1.12.2-2.1.5.0.jar                   | None                                     |
	| UCHIJAAAAAAAAA | resourceloader             | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAAAAAAA | simplecobblegen            | X.F.1                    | simplecobblegen-1.12.2-X.F.1.jar                  | None                                     |
	| UCHIJAAAAAAAAA | sourcebottles              | 1.0.1                    | SourceBottles-1.0.2.jar                           | None                                     |
	| UCHIJAAAAAAAAA | spikemod                   | 1.12-2.1.0               | spikemod-1.12-2.1.0.jar                           | None                                     |
	| UCHIJAAAAAAAAA | bq_standard                | 3.4.144                  | StandardExpansion-3.4.144.jar                     | None                                     |
	| UCHIJAAAAAAAAA | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                   | None                                     |
	| UCHIJAAAAAAAAA | theoneprobe                | 1.4.24                   | theoneprobe-1.12-1.4.24.jar                       | None                                     |
	| UCHIJAAAAAAAAA | thermalfoundation          | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | thermaldynamics            | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAA | tipthescales               | 1.0.1                    | TipTheScales-1.12.2-1.0.1.jar                     | None                                     |
	| UCHIJAAAAAAAAA | toastcontrol               | 1.7.1                    | Toast Control-1.12.2-1.7.1.jar                    | None                                     |
	| UCHIJAAAAAAAAA | tombstone                  | 3.1.2                    | tombstone-3.1.2-1.12.jar                          | None                                     |
	| UCHIJAAAAAAAAA | topaddons                  | 1.12.2-1.9.0             | topaddons-1.12.2-1.9.0.jar                        | None                                     |
	| UCHIJAAAAAAAAA | ts2k16                     | 1.2.9                    | TS2K16-1.2.9.jar                                  | None                                     |
	| UCHIJAAAAAAAAA | voidislandcontrol          | 1.4.3                    | voidislandcontrol-1.4.3.jar                       | None                                     |
	| UCHIJAAAAAAAAA | wct                        | 3.9.68                   | WirelessCraftingTerminal-1.12.2-3.9.68.jar        | None                                     |
	| UCHIJAAAAAAAAA | elulib                     | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |
	| UCHIJAAAAAAAAA | justthetips                | 1.12-1.0.1.1             | justthetips-1.12-1.0.1.1.jar                      | None                                     |
	| UCHIJAAAAAAAAA | teslacorelib_registries    | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                  | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
RandomPatches (randompatches-1.12.2-1.5.0.4.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	List of loaded APIs: 
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Base|API (1.0.0) from base-1.12.2-3.10.0.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.68.jar
		* BetterQuesting|API (3.1) from BetterQuesting-3.5.263.jar
		* BetterQuesting|API2 (3.1) from BetterQuesting-3.5.263.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* CharsetAPI (0.1) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Audio (0.0) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Carry (0.0) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Laser (0.0) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Lib (0.2) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Locks (0.1) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Pipes (0.3) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Storage (0.1) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Tape (0.0) from Charset-Lib-0.5.5.5.jar
		* CharsetAPI|Wires (0.3) from Charset-Lib-0.5.5.5.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.3.20-universal.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.18.jar
		* ExCompressum|API (1.0) from ExCompressum_1.12.2-3.0.24.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.344.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.344.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.11.2-212.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.12.0.216.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* PneumaticCraftApi (1.0) from pneumaticcraft-repressurized-1.12.2-0.8.0-267.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.35.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.24.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.68.jar
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Kane_Hart'/379, l='New Skies', x=-995.46, y=84.50, z=-998.24]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by EmosewaPixel** [comment]
Fixed
